version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - DB_URL=jdbc:h2:mem:sai_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - DB_DRIVER=org.h2.Driver
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama

volumes:
  ollama_storage:
